### PR TITLE
Sender, Recipient: set optional parameters only when are set

### PR DESCRIPTION
**Pull request by krajcikondra**

### CODE REVIEW

**Comment by Salamek** [comment]
@krajcikondra check if argument is filled should be in setters, not in constructor!

* Constructor should (usualy) pass arguments to setters withnout any logic
* Setters should handle validation

This PR has this bug then:

```php
$newSender = new Sender('Required parameter', 'Optional parameter with can be null');
//Attempt to reset RequiredParameter
$newSender->setRequiredParameter(null); // Throws exception which is OK
//Attempt to reset OptionalParameter
$newSender->setOptionalParameter(null); //Throws exception which is WRONG
```

so for example
change this in constructor: 

```php
if ($email) $this->setEmail($email);
```

back to 

```php
$this->setEmail($email);
```

and in setter change it to (use is_null check):

```php
public function setEmail($email)
{
    if (!is_null($email)
    {
        if (strlen($email) > 50) {
            throw new WrongDataException('$email is longer then 100 characters');
        }
        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            throw new WrongDataException('$email have invalid value');
        }
    }
    $this->email = $email;
}
```

So parameter is checked only when it is not NULL

**Comment by krajcikondra** [comment]
@Salamek ok, I edited PR by your comments.

**Comment by Salamek** [comment]
Looks good

**Comment by krajcikondra** [comment]
Thanks

**Pull request merged**
