### PR TITLE
[WIP] Fixes 

### PR DESCRIPTION
**Pull request by mirekratman**

### CODE REVIEW

**Comment by Salamek** [comment]
@mirekratman i quess that this is still WIP ? if so just prefix PR name with [WIP] and remove this prefix when you think that PR is ready for merge ;-)
GW

**Comment by mirekratman** [comment]
Hi, localy all test are passed, just scruntizer fails - will check it.

**Comment by Salamek** [comment]
@mirekratman HI, how it looks with this PR ? 
I'm getting requests to implement `GetNumberRange`... and that is implemented in this PR.
Do you need some help to finish this PR ?

**Comment by mirekratman** [comment]
@Salamek Hi, How fast you need this? I will be unavailable for a week from today. When I will be back i will finish it. The only reason why its not done is the fact it fails on Travis.
The code itself should be fine.

**Comment by Salamek** [comment]
@mirekratman well i think it can wait a while... Or i may merge it as is and fix travis issues my self (if i get to it before you do). So have a nice ?vacation? i guess  :smiley:

**Comment by mirekratman** [comment]
@Salamek ... yes you can. For me no problem. As you can see there is also unit test for this and it passes correctly.

**Pull request merged**
